:types:
  4: :cottage
  5: :marketplace
  7: :sawmill
  8: :mill
  10: :stonemason
  11: :foundry
  13: :townhouse
  14: :barracks
  15: :guard_house
  16: :training_ground
  17: :stable
  19: :shipyard
  20: :warehouse
  21: :castle
  22: :harbor
  23: :wall
  40: :guardian_tower
  41: :ranger_tower
  47: :woodcutters
  48: :querry
  49: :ironmine
  50: :farm

:building_plans:
  :castle_city: [8, 14, 15, 16, 17, 19, 22, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 50]
  :resource_city: [7, 8, 10, 11, 14, 15, 16, 47, 48, 49, 50]
  :for_new_city: [7, 10, 11, 47, 48, 49]
  :towers: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46]
  :all: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
  :all_without_corrage: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
  :all_without_corrage_and_warehouse: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
  :all_without_corrage_and_towers: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 47, 48, 49, 50]

:worlds:
  59:
    :settings:
      :session: 25f236c0-534b-4a14-be5d-e7ad3756595b
      :host: prodgame28.lordofultima.com
      :path: /139/Presentation/Service.svc/ajaxEndpoint/
      :cookie: s_ria=flash%2011%7Csilverlight%20not%20detected; s_cc=true; s_sq=%5B%5BB%5D%5D;__utma=74606733.156116825.1329120649.1331630032.1331634534.45;__utmc=74606733;__utmz=74606733.1331628169.43.28.utmcsr=prodgame28.lordofultima.com|utmccn=(referral)|utmcmd=referral|utmcct=/139/index.aspx
      :referer: http://prodgame28.lordofultima.com/139/index.aspx
    :cities:
      'first city':
        :id: 21168266
        :trade_minister: [:out, :none, :none, :in]
        :building_minister: :all_without_corrage
      'ironman':
        :id: 22085761
        :trade_minister: [:in, :in, :out, :out]
        :building_minister: :all
      'Kiev':
        :id: 21561490
        :trade_minister: [:none, :out, :none, :out]
        :building_minister: :all_without_corrage_and_towers
      'Krista':
        :id: 22085776
        :trade_minister: [:in, :in, :out, :out]
        :building_minister: :all_without_corrage_and_towers
      'Odessa':
        :id: 21430417
        :trade_minister: [:out, :out, :out, :in]
        :building_minister: :all_without_corrage_and_towers
      'Oslo':
        :id: 21233801
        :trade_minister: [:out, :out, :none, :none]
        :building_minister: :all_without_corrage
      'Rosa':
        :id: 22151308
        :trade_minister: [:in, :in, :in, :in]
        :building_minister: :all_without_corrage
      'Sevlush':
        :id: 21758098
        :trade_minister: [:out, :out, :out, :out]
        :building_minister: :all_without_corrage_and_towers
      'SOM':
        :id: 21954703
        :trade_minister: [:in, :in, :none, :out]
        :building_minister: :all_without_corrage_and_towers
      'Sprite':
        :id: 21627025
        :trade_minister: [:out, :out, :out, :out]
        :building_minister: :all_without_corrage_and_towers
      'Uzhgorod':
        :id: 21692553
        :trade_minister: [:out, :out, :out, :out]
        :building_minister: :all
      'Vinogradov':
        :id: 21758087
        :trade_minister: [:out, :out, :out, :out]
        :building_minister: :all
